# Generated by Django 5.0.14 on 2026-06-20 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturing', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('unit_of_measure', models.CharField(choices=[('PCS', 'Pieces'), ('KG', 'Kilograms'), ('M', 'Meters'), ('BOX', 'Boxes')], default='PCS', max_length=20)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('on_hand_qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('reserved_qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('procure_on_demand', models.BooleanField(default=False)),
                ('procurement_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('MANUFACTURING', 'Manufacturing')], default='PURCHASE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
                ('default_bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_products', to='manufacturing.bom')),
                ('default_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_products', to='purchase.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
