# Generated by Django 5.2.15 on 2026-06-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='customer_phone',
            field=models.CharField(blank=True, db_index=True, help_text="WhatsApp wa_id / phone in international format, no '+', e.g. 919876543210", max_length=32),
        ),
    ]
