# Generated by Django 5.2.15 on 2026-06-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesorder_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
