# Generated by Django 5.2.15 on 2026-06-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesorder_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='customer_phone',
            field=models.CharField(blank=True, db_index=True, help_text="Phone in international format, no '+', e.g. 919876543210", max_length=32),
        ),
    ]
