# Generated by Django 5.2.15 on 2026-06-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('BUSINESS_OWNER', 'Business Owner'), ('SALES_USER', 'Sales User'), ('PURCHASE_USER', 'Purchase User'), ('MANUFACTURING_USER', 'Manufacturing User'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('ACCOUNTANT', 'Accountant')], default='SALES_USER', max_length=50),
        ),
    ]
