# Generated by Django 5.2.15 on 2026-06-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('BUSINESS_OWNER', 'Business Owner'), ('SALES_USER', 'Sales User'), ('PURCHASE_USER', 'Purchase User'), ('MANUFACTURING_USER', 'Manufacturing User'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('ACCOUNTANT', 'Accountant'), ('TRADE_MANAGER', 'Trade Manager'), ('DOCUMENTATION_OFFICER', 'Documentation Officer'), ('FINANCE_MANAGER', 'Finance Manager'), ('AUDITOR', 'Auditor')], default='SALES_USER', max_length=50),
        ),
    ]
