# Generated by Django 5.0.14 on 2026-06-20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcurementTrigger",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity_needed", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(choices=[("QUEUED", "Queued"), ("PROCESSING", "Processing"), ("COMPLETED", "Completed"), ("FAILED", "Failed")], default="QUEUED", max_length=30)),
                ("document_type", models.CharField(blank=True, choices=[("purchase_order", "Purchase Order"), ("manufacturing_order", "Manufacturing Order")], max_length=40)),
                ("document_id", models.UUIDField(blank=True, null=True)),
                ("document_number", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_triggers', to=settings.AUTH_USER_MODEL)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_triggers', to='products.product')),
            ],
        ),
    ]