# Generated by Django 5.2.15 on 2026-06-20 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the document file', max_length=255)),
                ('blockchain_txn', models.CharField(db_index=True, help_text='Blockchain transaction hash', max_length=255)),
                ('network', models.CharField(default='polygon-amoy', max_length=100)),
                ('block_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_APPROVED', 'Order Approved'), ('INVOICE_GENERATED', 'Invoice Generated'), ('SHIPMENT_DISPATCHED', 'Shipment Dispatched'), ('SHIPMENT_DELIVERED', 'Shipment Delivered'), ('CUSTOMS_CLEARED', 'Customs Cleared'), ('PAYMENT_RECEIVED', 'Payment Received'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_VERIFIED', 'Document Verified'), ('STATUS_CHANGED', 'Status Changed')], db_index=True, max_length=100)),
                ('reference_id', models.CharField(db_index=True, help_text='UUID or order number of the related record', max_length=100)),
                ('reference_model', models.CharField(blank=True, help_text='Model name, e.g. ExportOrder', max_length=100)),
                ('data_hash', models.CharField(help_text='SHA-256 hash of the event data', max_length=255)),
                ('blockchain_txn', models.CharField(db_index=True, help_text='Blockchain transaction hash', max_length=255)),
                ('network', models.CharField(default='polygon-amoy', max_length=100)),
                ('block_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event context')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
