# Generated by Django 5.2.15 on 2026-06-20 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0001_initial'),
        ('foreign_trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchaindocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_records', to='foreign_trade.tradedocument'),
        ),
        migrations.AddIndex(
            model_name='blockchainauditlog',
            index=models.Index(fields=['event_type', 'created_at'], name='blockchain__event_t_01415a_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainauditlog',
            index=models.Index(fields=['reference_id'], name='blockchain__referen_00a40a_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaindocument',
            index=models.Index(fields=['document_hash'], name='blockchain__documen_2cd6a1_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaindocument',
            index=models.Index(fields=['blockchain_txn'], name='blockchain__blockch_8e1c75_idx'),
        ),
    ]
