# Generated by Django 5.2.15 on 2026-06-20 09:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('cost_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='bom',
            options={'ordering': ['reference'], 'verbose_name': 'Bill of Materials', 'verbose_name_plural': 'Bills of Materials'},
        ),
        migrations.RenameField(
            model_name='bom',
            old_name='description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='bom',
            name='code',
        ),
        migrations.AddField(
            model_name='bom',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='product',
            field=models.ForeignKey(blank=True, help_text='The finished product this BOM produces. Leave blank for templates.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='products.product'),
        ),
        migrations.AddField(
            model_name='bom',
            name='product_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Quantity of finished product produced by one run of this BOM.', max_digits=10),
        ),
        migrations.AddField(
            model_name='bom',
            name='reference',
            field=models.CharField(db_index=True, default='BOM-LEGACY', help_text='e.g. BOM-001', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BOMComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=12)),
                ('uom', models.CharField(help_text='Unit of Measure (copied from component default, can be overridden).', max_length=20)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='manufacturing.bom')),
                ('component', models.ForeignKey(help_text='Raw material or sub-assembly consumed.', on_delete=django.db.models.deletion.PROTECT, related_name='used_in_boms', to='products.product')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BOMOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. 'Cut wood panels', 'Sand & finish'", max_length=255)),
                ('duration_minutes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected duration in minutes.', max_digits=8)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='manufacturing.bom')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='manufacturing.workcenter')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
    ]
