# Generated by Django 5.2.15 on 2026-06-20 09:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_bom_full'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, help_text='e.g. MO-0001 — auto-generated on save.', max_length=50, unique=True)),
                ('qty_to_produce', models.DecimalField(decimal_places=2, help_text='Number of finished units to produce.', max_digits=12)),
                ('qty_produced', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Units actually produced so far.', max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('bom', models.ForeignKey(blank=True, help_text='Source BOM. Components & operations are copied at confirmation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_orders', to='manufacturing.bom')),
                ('product', models.ForeignKey(help_text='The finished product to manufacture.', on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_orders', to='products.product')),
            ],
            options={
                'verbose_name': 'Manufacturing Order',
                'verbose_name_plural': 'Manufacturing Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MOComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty_required', models.DecimalField(decimal_places=4, help_text='Total required (scaled to MO qty_to_produce).', max_digits=12)),
                ('qty_consumed', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Quantity actually consumed (set at produce step).', max_digits=12)),
                ('uom', models.CharField(max_length=20)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('mo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='manufacturing.manufacturingorder')),
                ('product', models.ForeignKey(help_text='Raw material / sub-assembly to consume.', on_delete=django.db.models.deletion.PROTECT, related_name='mo_components', to='products.product')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('duration_expected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected duration in minutes (copied from BOM operation).', max_digits=8)),
                ('duration_actual', models.DecimalField(blank=True, decimal_places=2, help_text='Actual time taken in minutes (filled at completion).', max_digits=8, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], db_index=True, default='PENDING', max_length=20)),
                ('mo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='manufacturing.manufacturingorder')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='manufacturing.workcenter')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
    ]
