# Generated by Django 5.2.15 on 2026-06-20 19:41

import apps.foreign_trade.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-2/3', max_length=3, unique=True)),
                ('region', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='ISO 4217', max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, help_text='Rate relative to base currency (e.g. 1 USD = X)', max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Incoterm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExportOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('shipping_method', models.CharField(choices=[('SEA', 'Sea Freight'), ('AIR', 'Air Freight'), ('ROAD', 'Road Transport'), ('RAIL', 'Rail Freight'), ('MULTIMODAL', 'Multimodal')], default='SEA', max_length=20)),
                ('port_of_loading', models.CharField(blank=True, max_length=255)),
                ('port_of_destination', models.CharField(blank=True, max_length=255)),
                ('container_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUOTATION', 'Quotation'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_orders', to='foreign_trade.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_orders', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_orders', to='foreign_trade.currency')),
                ('incoterm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_orders', to='foreign_trade.incoterm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_invoices', to='foreign_trade.currency')),
                ('export_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='foreign_trade.exportorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500)),
                ('hs_code', models.CharField(blank=True, help_text='Harmonized System code', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('export_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='foreign_trade.exportorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('container_number', models.CharField(blank=True, max_length=100)),
                ('eta', models.DateField(blank=True, help_text='Estimated Time of Arrival', null=True)),
                ('customs_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('DOCUMENTS_SUBMITTED', 'Documents Submitted'), ('UNDER_REVIEW', 'Under Review'), ('CLEARED', 'Cleared'), ('HELD', 'Held')], db_index=True, default='NOT_STARTED', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('IN_TRANSIT', 'In Transit'), ('CUSTOMS', 'Customs'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_orders', to='foreign_trade.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_orders', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_orders', to='foreign_trade.currency')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500)),
                ('hs_code', models.CharField(blank=True, help_text='Harmonized System code', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('import_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='foreign_trade.importorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TradeCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='foreign_trade.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exportorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_orders', to='foreign_trade.tradecustomer'),
        ),
        migrations.CreateModel(
            name='TradeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('COMMERCIAL_INVOICE', 'Commercial Invoice'), ('PACKING_LIST', 'Packing List'), ('BILL_OF_LADING', 'Bill of Lading'), ('CERTIFICATE_OF_ORIGIN', 'Certificate of Origin'), ('INSURANCE_CERTIFICATE', 'Insurance Certificate'), ('CUSTOMS_DECLARATION', 'Customs Declaration'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.foreign_trade.models.trade_document_upload_path)),
                ('version', models.PositiveIntegerField(default=1)),
                ('object_id', models.UUIDField()),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('TAMPERED', 'Tampered'), ('UNVERIFIED', 'Unverified')], db_index=True, default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeSupplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='foreign_trade.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='importorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_orders', to='foreign_trade.tradesupplier'),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('object_id', models.UUIDField()),
                ('carrier', models.CharField(blank=True, max_length=255)),
                ('tracking_number', models.CharField(blank=True, max_length=255)),
                ('vessel_name', models.CharField(blank=True, max_length=255)),
                ('port_of_loading', models.CharField(blank=True, max_length=255)),
                ('port_of_destination', models.CharField(blank=True, max_length=255)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('AT_PORT', 'At Port'), ('CUSTOMS', 'Customs'), ('DELIVERED', 'Delivered')], db_index=True, default='PENDING', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='foreign_tra_content_aba249_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='exportorder',
            index=models.Index(fields=['status', 'created_at'], name='foreign_tra_status_6fdb90_idx'),
        ),
        migrations.AddIndex(
            model_name='tradedocument',
            index=models.Index(fields=['content_type', 'object_id', 'document_type'], name='foreign_tra_content_40b5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='importorder',
            index=models.Index(fields=['status', 'created_at'], name='foreign_tra_status_2399ce_idx'),
        ),
    ]
