# Generated by Django 5.2.15 on 2026-06-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs__module_dd5bd8_idx',
            old_name='audit_logs_mo_act_ti_4d7a9c_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs__record__2ab44b_idx',
            old_name='audit_logs_recor_4c8d77_idx',
        ),
    ]
